approved = [
    "mit",
    "apache-2.0",
    "bsd-3-clause",
    "bsd-2-clause",
    "mpl-2.0",
]

ignored = [
    "github.com/aliyun/aliyun-oss-go-sdk",
    "github.com/ghodss/yaml", # MIT
    "sigs.k8s.io/yaml", # MIT
    "github.com/gogo/protobuf", # Google
    "github.com/golang/protobuf",
    "google.golang.org/protobuf",

    "github.com/davecgh/go-spew", # ISC license
    "github.com/howeyc/gopass", # ISC license
    "github.com/oracle/oci-go-sdk", # UPL-1.0
    "gopkg.in/square/go-jose.v2", # Apache 2.0
    "github.com/alecthomas/template", # BSD-3
    "github.com/alecthomas/units", # MIT
    "gopkg.in/alecthomas/kingpin.v2", # MIT
    "github.com/prometheus/statsd_exporter", # Apache 2.0
]
