approved = [
    "mit",
    "apache-2.0",
    "bsd-3-clause",
    "bsd-2-clause",
    "mpl-2.0",
]

ignored = [
    "github.com/aliyun/aliyun-oss-go-sdk",
    "github.com/ghodss/yaml",
    "github.com/gogo/protobuf",
    "github.com/golang/protobuf",
    "github.com/stretchr/testify",
    "github.com/jmespath/go-jmespath",
    "github.com/go-openapi/spec",
    "github.com/magiconair/properties",
    "github.com/pmezard/go-difflib",
    "github.com/shopspring/decimal",
    "github.com/globalsign/mgo",

    "github.com/davecgh/go-spew", # ISC license
    "github.com/howeyc/gopass", # ISC license
    "github.com/oracle/oci-go-sdk", # UPL-1.0

    "git.apache.org/thrift.git",
    "go.opencensus.io",
    "google.golang.org/api",
    "google.golang.org/grpc",
    "google.golang.org/genproto",
    "contrib.go.opencensus.io/exporter/ocagent",
    "cloud.google.com/go",
    "contrib.go.opencensus.io/exporter/jaeger",
    "contrib.go.opencensus.io/exporter/prometheus",
    "sigs.k8s.io/yaml"
]
