[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.16.22"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "v1.3.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.3.0"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "v2.1.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.9.2"

[[constraint]]
  name = "github.com/prometheus/common"
  revision = "e5b036cc37a466a0af27d604d1ee500211d16d6a"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "3.2.0"

[[constraint]]
  name = "github.com/gin-contrib/cors"
  version = "v1.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.3.0"

[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "5dab4167f31cbd76b407f1486c86b40748bc5073"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "v1.3.1"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "v1.0.3"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "v11.3.1"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "v24.1.0"

[[constraint]]
  name = "github.com/gin-contrib/static"
  revision = "cf5e10bbd933040ff603b7f0fb85510bae9916f0"

[[constraint]]
  name = "github.com/banzaicloud/go-gin-prometheus"
  revision = "fa3b20bd0ba938372f83549aa82ba0d247ac7e7a"

[[constraint]]
  name = "github.com/oracle/oci-go-sdk"
  version = "v3.4.0"

[[constraint]]
  name = "github.com/aliyun/alibaba-cloud-sdk-go"
  version = "1.51.1"

# master: Could not introduce github.com/aliyun/alibaba-cloud-sdk-go@1.51.1,
# as it has a dependency on github.com/jmespath/go-jmespath with constraint ^0.2.2,
# which has no overlap with the following existing constraints:
#	c2b33e84 from github.com/aws/aws-sdk-go@v1.16.11
[[override]]
  revision = "c2b33e84"
  name = "github.com/jmespath/go-jmespath"

[[constraint]]
  name = "go.opencensus.io"
  version = "0.18.0"

[[constraint]]
  name = "github.com/moogar0880/problems"
  version = "0.1.0"

[[constraint]]
  name = "github.com/goph/logur"
  version = "0.10.0"

[[constraint]]
  name = "github.com/goph/emperror"
  version = "0.16.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/asaskevich/EventBus"
  revision = "d46933a9"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v8"
  version = "v8.18.2"

[[constraint]]
  name = "github.com/gomodule/redigo"
  version = "2.0.0"
