version: 2.1

orbs:
    helm: banzaicloud/helm@0.0.3

executors:
    docker:
        docker:
            -
                image: circleci/golang:1.12
                environment:
                    GOFLAGS: -mod=readonly

commands:
    restore_build_cache:
        description: Restore build cache
        steps:
            -
                restore_cache:
                    name: Restore build dependencies
                    keys:
                        - build-deps-v1-{{ .Branch }}-{{ checksum "Makefile" }}

    restore_go_module_cache:
        description: Restore Go module cache
        steps:
            -
                restore_cache:
                    name: Restore Go module cache
                    keys:
                        - gomod-v1-{{ .Branch }}-{{ checksum "go.sum" }}
                        - gomod-v1-{{ .Branch }}
                        - gomod-v1-master
                        - gomod-v1

jobs:
    dependencies:
        executor: docker

        steps:
            - checkout
            - restore_go_module_cache

            -
                run:
                    name: Download Go module cache
                    command: go mod download

            -
                run:
                      name: Install build dependencies
                      command: make -j bin/golangci-lint bin/licensei bin/gotestsum

            -
                save_cache:
                    name: Save Go module cache
                    key: gomod-v1-{{ .Branch }}-{{ checksum "go.sum" }}
                    paths:
                        - /go/pkg/mod

            -
                save_cache:
                    name: Save build dependencies
                    key: build-deps-v1-{{ .Branch }}-{{ checksum "Makefile" }}
                    paths:
                        - bin/

    static-checks:
        executor: docker

        steps:
            - checkout
            - restore_build_cache
            - restore_go_module_cache

            -
                restore_cache:
                    name: Restore license cache
                    keys:
                        - licensei-v1-{{ .Branch }}-{{ checksum "go.sum" }}
                        - licensei-v1-{{ .Branch }}
                        - licensei-v1-master
                        - licensei-v1

            -
                run:
                    name: Download license information for dependencies
                    command: make license-cache

            -
                save_cache:
                    name: Save license cache
                    key: licensei-v1-{{ .Branch }}-{{ checksum "go.sum" }}
                    paths:
                        - .licensei.cache

            -
                run:
                    name: Check dependency licenses
                    command: make license-check

            -
                run:
                    name: Run linter
                    command: make lint

    build:
        executor: docker

        steps:
            - checkout
            - restore_build_cache
            - restore_go_module_cache

            -
                run:
                    name: Build
                    command: make build

    unit-tests:
        executor: docker

        steps:
            - checkout
            - restore_build_cache
            - restore_go_module_cache

            -
                run:
                    name: Run tests
                    command: TEST_PKGS=$(echo `go list ./... | circleci tests split`) TEST_REPORT_NAME=results_${CIRCLE_NODE_INDEX}.xml make test

            -
                store_test_results:
                    path: build/test_results/

    integration-tests:
        docker:
            -
                image: circleci/golang:1.12
                environment:
                    GOFLAGS: -mod=readonly
            -
                image: redis:5.0
            -
                image: cassandra:3.11
                environment:
                    MAX_HEAP_SIZE: 1024m
                    HEAP_NEWSIZE: 256m
        executor: docker

        steps:
            - checkout
            - restore_build_cache
            - restore_go_module_cache

            -
                run:
                    name: Run integration tests
                    command: TEST_PKGS=$(echo `go list ./... | circleci tests split`) TEST_REPORT_NAME=results_${CIRCLE_NODE_INDEX}.xml make test-integration

            -
                store_test_results:
                    path: build/test_results/

workflows:
    version: 2
    ci:
        jobs:
            - dependencies
            - static-checks:
                  requires:
                      - dependencies
            - build:
                  requires:
                      - dependencies
            - unit-tests:
                  requires:
                      - dependencies
            - integration-tests:
                  requires:
                      - dependencies

    helm-chart:
        jobs:
            - helm/lint-chart:
                  chart-path: charts/cloudinfo
                  filters:
                      tags:
                          ignore: /.*/

            - helm/publish-chart:
                  context: helm
                  chart-path: charts/cloudinfo
                  filters:
                      branches:
                          ignore: /.*/
                      tags:
                          only: /\/chart/cloudinfo\/\d+.\d+.\d+/
