version: 2.1

orbs:
    helm: banzaicloud/helm@0.0.3
    docker: circleci/docker@0.5.13

executors:
    go:
        parameters:
            build_image:
                type: string
                default: "circleci/golang"
                description: Go build image
            go_version:
                type: string
                default: "1.13"
                description: Go build image version
        docker:
            -   image: << parameters.build_image >>:<< parameters.go_version >>
                environment:
                    GOFLAGS: -mod=readonly

jobs:
    static-checks:
        executor: go

        steps:
            - checkout

            -   restore_cache:
                    name: Restore license cache
                    keys:
                        - licensei-v1-{{ .Branch }}-{{ checksum "go.sum" }}
                        - licensei-v1-{{ .Branch }}
                        - licensei-v1-master
                        - licensei-v1

            -   run:
                    name: Download license information for dependencies
                    command: make license-cache

            -   save_cache:
                    name: Save license cache
                    key: licensei-v1-{{ .Branch }}-{{ checksum "go.sum" }}
                    paths:
                        - .licensei.cache

            -   run:
                    name: Check dependency licenses
                    command: make license-check

            -   run:
                    name: Run linter
                    command: make lint

    build:
        executor: go

        steps:
            - checkout

            -   run:
                    name: Build
                    command: make build

    unit-tests:
        executor: go

        steps:
            - checkout

            -   run:
                    name: Run tests
                    command: |
                        if [ $CIRCLE_NODE_TOTAL -gt 1 ]; then
                            export TEST_PKGS=$(echo `go list ./... | circleci tests split`)
                            export TEST_REPORT_NAME=results_${CIRCLE_NODE_INDEX}.xml
                        fi

                        make test

            -   store_test_results:
                    path: build/test_results/

    integration-tests:
        executor: go
        docker:
            -   image: circleci/golang:1.13
                environment:
                    GOFLAGS: -mod=readonly
            -   image: redis:5.0
            -   image: cassandra:3.11
                environment:
                    MAX_HEAP_SIZE: 1024m
                    HEAP_NEWSIZE: 256m

        steps:
            - checkout

            -   run:
                    name: Run integration tests
                    command: |
                        if [ $CIRCLE_NODE_TOTAL -gt 1 ]; then
                            export TEST_PKGS=$(echo `go list ./... | circleci tests split`)
                            export TEST_REPORT_NAME=results_${CIRCLE_NODE_INDEX}.xml
                        fi

                        make test-integration

            -   store_test_results:
                    path: build/test_results/

    docker-release:
        executor: docker/machine
        parameters:
            tag:
                default: $CIRCLE_SHA1
                description: 'Image tag'
                type: string
            extra_build_args:
                default: ''
                description: >
                    Extra flags to pass to docker build. For examples
                type: string
            image:
                description: Name of image to build
                type: string
            registry:
                default: docker.io
                description: |
                    Name of registry to use, defaults to docker.io
                type: string
        steps:
            - checkout
            - docker/check

            -   docker/build:
                    extra_build_args: <<parameters.extra_build_args>>
                    registry: <<parameters.registry>>
                    image: <<parameters.image>>
                    tag: $CIRCLE_SHA1

            -   run:
                    name: Tag release
                    command: |
                        docker tag <<parameters.image>>:$CIRCLE_SHA1 <<parameters.registry>>/<<parameters.image>>:<<parameters.tag>>

            -   docker/push:
                    registry: <<parameters.registry>>
                    image: <<parameters.image>>
                    tag: <<parameters.tag>>

            -   run:
                    name: Check version
                    command: |
                        if ! echo "${CIRCLE_TAG}" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
                          echo 'Unstable version. Skipping further steps.'
                          circleci step halt
                        fi

            -   run:
                    name: Tag latest
                    command: |
                        docker tag <<parameters.image>>:$CIRCLE_SHA1 <<parameters.registry>>/<<parameters.image>>:latest

            -   docker/push:
                    registry: <<parameters.registry>>
                    image: <<parameters.image>>
                    tag: latest

workflows:
    version: 2
    ci:
        jobs:
            - static-checks
            - build
            - unit-tests
            - integration-tests
            -   docker/publish:
                    name: Build docker image
                    deploy: false
                    image: banzaicloud/cloudinfo
                    tag: $CIRCLE_BRANCH
                    filters:
                        branches:
                            ignore: master
            -   docker/publish:
                    name: Publish master docker image
                    context: dockerhub
                    deploy: true
                    image: banzaicloud/cloudinfo
                    tag: master
                    requires:
                        - build
                        - static-checks
                        - unit-tests
                        - integration-tests
                    filters:
                        branches:
                            only: master
            -   docker-release:
                    name: Publish tagged & latest docker image
                    context: dockerhub
                    image: banzaicloud/cloudinfo
                    tag: $CIRCLE_TAG
                    filters:
                        tags:
                            only: /^[0-9]+\.[0-9]+\.[0-9]+(?:-(?:dev|rc)\.[0-9]+)?$/
                        branches:
                            ignore: /.*/

    helm-chart:
        jobs:
            -   helm/lint-chart:
                    chart-path: charts/cloudinfo
                    filters:
                        tags:
                            ignore: /.*/

            -   helm/publish-chart:
                    context: helm
                    chart-path: charts/cloudinfo
                    filters:
                        branches:
                            ignore: /.*/
                        tags:
                            only: /chart\/cloudinfo\/\d+.\d+.\d+/
