isstatic: true
name: pke
provider: amazon
source: compute
regions:
    -   name: AWS GovCloud (US-East)
        id: us-gov-east-1
        data:
            zones:
                strategy: exclude
            images:
                strategy: exclude
            versions:
                strategy: exact
                data:
                    -   location: us-gov-east-1
                        versions:
                            - 1.15.12
                            - 1.16.11
                            - 1.17.7
                            - 1.18.4
                        default: 1.17.7
            vms:
                strategy: include
                data:
                    -   type: t2.small
                    -   type: t2.medium
                    -   type: t2.large
                    -   type: t2.xlarge
                    -   type: t2.2xlarge
                    -   type: m3.medium
                    -   type: m3.large
                    -   type: m3.xlarge
                    -   type: m3.2xlarge
                    -   type: m4.large
                    -   type: m4.xlarge
                    -   type: m4.2xlarge
                    -   type: m4.4xlarge
                    -   type: m4.10xlarge
                    -   type: m5.large
                    -   type: m5.xlarge
                    -   type: m5.2xlarge
                    -   type: m5.4xlarge
                    -   type: m5.12xlarge
                    -   type: m5.24xlarge
                    -   type: c4.large
                    -   type: c4.xlarge
                    -   type: c4.2xlarge
                    -   type: c4.4xlarge
                    -   type: c4.8xlarge
                    -   type: c5.large
                    -   type: c5.xlarge
                    -   type: c5.2xlarge
                    -   type: c5.4xlarge
                    -   type: c5.9xlarge
                    -   type: c5.18xlarge
                    -   type: i3.large
                    -   type: i3.xlarge
                    -   type: i3.2xlarge
                    -   type: i3.4xlarge
                    -   type: i3.8xlarge
                    -   type: i3.16xlarge
                    -   type: r3.xlarge
                    -   type: r3.2xlarge
                    -   type: r3.4xlarge
                    -   type: r3.8xlarge
                    -   type: r4.large
                    -   type: r4.xlarge
                    -   type: r4.2xlarge
                    -   type: r4.4xlarge
                    -   type: r4.8xlarge
                    -   type: r4.16xlarge
                    -   type: x1.16xlarge
                    -   type: x1.32xlarge
                    -   type: p2.xlarge
                    -   type: p2.8xlarge
                    -   type: p2.16xlarge
                    -   type: p3.2xlarge
                    -   type: p3.8xlarge
                    -   type: p3.16xlarge

    -   name: AWS GovCloud (US-West)
        id: us-gov-west-1
        data:
            zones:
                strategy: exclude
            images:
                strategy: exclude
            versions:
                strategy: exact
                data:
                    -   location: us-gov-west-1
                        versions:
                            - 1.15.12
                            - 1.16.11
                            - 1.17.7
                            - 1.18.4
                        default: 1.17.7
            vms:
                strategy: include
                data:
                    -   type: t2.small
                    -   type: t2.medium
                    -   type: t2.large
                    -   type: t2.xlarge
                    -   type: t2.2xlarge
                    -   type: m3.medium
                    -   type: m3.large
                    -   type: m3.xlarge
                    -   type: m3.2xlarge
                    -   type: m4.large
                    -   type: m4.xlarge
                    -   type: m4.2xlarge
                    -   type: m4.4xlarge
                    -   type: m4.10xlarge
                    -   type: m5.large
                    -   type: m5.xlarge
                    -   type: m5.2xlarge
                    -   type: m5.4xlarge
                    -   type: m5.12xlarge
                    -   type: m5.24xlarge
                    -   type: c4.large
                    -   type: c4.xlarge
                    -   type: c4.2xlarge
                    -   type: c4.4xlarge
                    -   type: c4.8xlarge
                    -   type: c5.large
                    -   type: c5.xlarge
                    -   type: c5.2xlarge
                    -   type: c5.4xlarge
                    -   type: c5.9xlarge
                    -   type: c5.18xlarge
                    -   type: i3.large
                    -   type: i3.xlarge
                    -   type: i3.2xlarge
                    -   type: i3.4xlarge
                    -   type: i3.8xlarge
                    -   type: i3.16xlarge
                    -   type: r3.xlarge
                    -   type: r3.2xlarge
                    -   type: r3.4xlarge
                    -   type: r3.8xlarge
                    -   type: r4.large
                    -   type: r4.xlarge
                    -   type: r4.2xlarge
                    -   type: r4.4xlarge
                    -   type: r4.8xlarge
                    -   type: r4.16xlarge
                    -   type: x1.16xlarge
                    -   type: x1.32xlarge
                    -   type: p2.xlarge
                    -   type: p2.8xlarge
                    -   type: p2.16xlarge
                    -   type: p3.2xlarge
                    -   type: p3.8xlarge
                    -   type: p3.16xlarge
