isstatic: true
name: pke
provider: azure
source: aks
regions:
    -   name: Central US
        id: centralus
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: centralus
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: East US
        id: eastus
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: eastus
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: East US 2
        id: eastus2
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: eastus2
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: West US 2
        id: westus2
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: westus2
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: France Central
        id: francecentral
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: francecentral
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: North Europe
        id: northeurope
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: northeurope
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: UK South
        id: uksouth
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: uksouth
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: West Europe
        id: westeurope
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: westeurope
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: Japan East
        id: japaneast
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: japaneast
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: Southeast Asia
        id: southeastasia
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: southeastasia
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: Australia Southeast
        id: australiasoutheast
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: australiasoutheast
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: East Asia
        id: eastasia
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: eastasia
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: Canada Central
        id: canadacentral
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: canadacentral
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: Canada East
        id: canadaeast
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: canadaeast
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: Korea South
        id: koreasouth
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: koreasouth
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: Japan West
        id: japanwest
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: japanwest
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: South India
        id: southindia
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: southindia
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: West US
        id: westus
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: westus
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: South Central US
        id: southcentralus
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: southcentralus
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: North Central US
        id: northcentralus
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: northcentralus
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: Australia East
        id: australiaeast
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: australiaeast
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: Central India
        id: centralindia
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: centralindia
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: UK West
        id: ukwest
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: ukwest
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
    -   name: Korea Central
        id: koreacentral
        data:
            zones:
                strategy: exclude
            images:
                strategy: exact
            versions:
                strategy: exact
                data:
                    -   location: koreacentral
                        versions:
                            - 1.19.10
                            - 1.20.6
                            - 1.21.0
                        default: 1.19.10
            vms:
                strategy: exclude
