apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloudinfo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cloudinfo.name" . }}
    helm.sh/chart: {{ include "cloudinfo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  config.yaml: |
    log:
      level: {{ .Values.app.logLevel }}
    metrics:
      enabled: {{ .Values.metrics.enabled }}
    config:
      vault:
{{ toYaml .Values.app.vault | indent 8 }}
    store:
      redis:
        enabled: {{ .Values.store.redis.enabled }}
        host: {{ include "cloudinfo.redis.host" . }}
        port: {{ include "cloudinfo.redis.port" . }}
    provider:
{{ toYaml .Values.providers | indent 6 }}
