apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudinfo.frontend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cloudinfo.name" . }}
    app.kubernetes.io/component: "frontend"
    helm.sh/chart: {{ include "cloudinfo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "cloudinfo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cloudinfo.frontend.fullname" . }}-metrics
  labels:
    app.kubernetes.io/name: {{ include "cloudinfo.name" . }}
    app.kubernetes.io/component: "frontend"
    helm.sh/chart: {{ include "cloudinfo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.port }}
      name: metrics
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: {{ include "cloudinfo.name" . }}
    app.kubernetes.io/component: "frontend"
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cloudinfo.scraper.fullname" . }}-metrics
  labels:
    app.kubernetes.io/name: {{ include "cloudinfo.name" . }}
    app.kubernetes.io/component: "scraper"
    helm.sh/chart: {{ include "cloudinfo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.metrics.port }}
      name: metrics
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: {{ include "cloudinfo.name" . }}
    app.kubernetes.io/component: "scraper"
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
